# Generated by Django 4.0.5 on 2022-08-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0003_admin'),
        ('food_app', '0003_food_image_food_image_url_food_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.customer')),
            ],
        ),
    ]
