# Generated by Django 4.0.5 on 2022-10-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('food_app', '0002_initial'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.food'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.customer'),
        ),
        migrations.AddField(
            model_name='billinglocation',
            name='request_id',
            field=models.ForeignKey(db_column='order_request_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='order_app.order', to_field='request_id'),
        ),
    ]
