# Generated by Django 4.0.5 on 2022-10-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinglocation',
            name='request_id',
            field=models.ForeignKey(db_column='order_request_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order_app.order', to_field='request_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('success', 'Accepted'), ('failed', 'Rejected')], default='pending', max_length=20),
        ),
    ]
