# Generated by Django 4.0.6 on 2022-09-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_billinglocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinglocation',
            old_name='order_id',
            new_name='order',
        ),
    ]
