# Generated by Django 4.0.5 on 2022-10-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_billinglocation_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinglocation',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('failed', 'Rejected'), ('success', 'Accepted'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='request_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
