# Generated by Django 4.0.5 on 2022-10-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_remove_billinglocation_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('failed', 'Rejected'), ('delivered', 'Delivered'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('success', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='billinglocation',
            table='billing_location',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
