# Generated by Django 4.0.5 on 2022-10-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_alter_order_order_status_alter_billinglocation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('pending', 'Pending'), ('success', 'Accepted'), ('failed', 'Rejected')], default='pending', max_length=20),
        ),
    ]
