# Generated by Django 4.0.5 on 2022-07-30 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('restaurant_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Admin',
                'db_table': 'Admin',
            },
            bases=('user_app.user',),
        ),
    ]
