# Generated by Django 4.0.5 on 2022-07-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
