# Generated by Django 4.0.5 on 2022-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
