# Generated by Django 4.0.5 on 2022-07-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurantadmin',
            managers=[
            ],
        ),
    ]
