# Generated by Django 4.0.6 on 2022-08-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_alter_restaurantadmin_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantadmin',
            old_name='restaurant_name',
            new_name='restaurant',
        ),
    ]
